### PR TITLE
Feature dependencies upgrade

### PR DESCRIPTION
**Pull request by ihorml**
```
{
    "angular-ui-notification": "^0.3.6", // latest
    "clipboard": "^2.0.6", // upgraded to 2.0.11
    "extract-zip": "^2.0.0", //upgraded to 2.0.1
    "highcharts": "^8.1.2", // upgraded to 10.3.2
    "md5-file": "^5.0.0", // latest
    "ngstorage": "^0.3.11", // latest
    "angular": ">=1.7.9", // upgrade to 1.8.3
    "angular-animate": "1.7.8", // upgrade to 1.8.3
    "angular-aria": "1.7.8", // upgrade to 1.8.3
    "angular-echarts-lite": "1.1.0", // latest
    "angular-google-analytics": "1.1.8", // latest
    "angular-loader": "1.7.8", // upgrade to 1.8.3
    "angular-loading-bar": "0.9.0", // latest
    "angular-route": "1.7.8", // upgrade to 1.8.3
    "angular-translate": "2.18.1", // upgraded to 2.19.0
    "angular-translate-loader-static-files": "2.18.1",
    "angular-ui-bootstrap": "2.5.6", // latest
    "angular-websocket": "2.0.1", // latest
    "archiver": "^4.0.1", // latest
    "bootstrap": "3.4.1", // keep as dependency for angular-ui-bootstrap
    "components-font-awesome": "5.9.0", // latest
    "copy-webpack-plugin": "^5.1.2",
    "echarts": "4.2.1", // keep as dependecy for angular-echarts-lite
    "git-rev-sync": "^3.0.1",
    "html-webpack-plugin": "3.2.0",
    "jdenticon": "2.2.0", // upgrade to 3.2.0
    "jquery": "^3.5.1", // upgrade to 3.6.1
    "js-sha256": "0.9.0", // latest
    "webpack": "^4.39.2",
    "webpack-cli": "^3.3.7",
    "webpack-dev-server": "^3.11.0"
}
```

One thing left is to upgrade the webpack & its packages if it is necessary. I'm pretty sure it will require changes to webpack config but can't estimate it

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
I did a clean install with Node 16, I get errors on startup. Which Node version did you use?

**Comment by ihorml** [comment]
@sschiessl-bcp can you provide the details? I've tried on nvm 14 / 16 and both works fine

**Comment by sschiessl-bcp** [comment]
image

**Comment by sschiessl-bcp** [comment]
Installation
image

Start
```
[schiessl@secp256k1 test]$ yarn run start
yarn run v1.22.17
warning package.json: License should be a valid SPDX license expression
$ webpack-dev-server --mode=development
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9000/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.11:9000/
<i> [webpack-dev-server] Content not from webpack is served from '/home/schiessl/Projekte/BitShares-Insight/test/dist' directory
assets by path images/ 3.34 MiB 376 assets
assets by path charting_library/ 6.01 MiB 87 assets
assets by path html/ 355 KiB
  assets by path html/*.html 172 KiB 36 assets
  assets by path html/*.css 184 KiB 6 assets
assets by path webfonts/ 2.62 MiB 15 assets
assets by path *.js 10.6 MiB
  asset vendor.bundle.js 8.57 MiB [emitted] (name: vendor)
  asset app.bundle.js 2.07 MiB [emitted] (name: app)
assets by path i18n/*.json 27.9 KiB
  asset i18n/en.json 19.9 KiB [emitted] [from: app/i18n/en.json] [copied]
  asset i18n/zh.json 8.04 KiB [emitted] [from: app/i18n/zh.json] [copied]
asset favicon.ico 13.7 KiB [emitted] [from: app/favicon.ico] [copied]
asset index.html 2.28 KiB [emitted]
runtime modules 54.8 KiB 27 modules
modules by path ./node_modules/ 8.46 MiB 1158 modules
modules by path ./app/ 355 KiB
  modules by path ./app/sections/ 102 KiB 47 modules
  modules by path ./app/core/*.js 218 KiB 14 modules
  modules by path ./app/ui/*.js 28.9 KiB 12 modules
  modules by path ./app/*.js 3.04 KiB 2 modules
  modules by path ./app/highcharts/*.js 2.76 KiB 2 modules
  modules by path ./app/chart/*.js 293 bytes 2 modules
+ 11 modules

ERROR in ./node_modules/ws/lib/BufferPool.js 7:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/lib/Receiver.js 10:17-40
 @ ./node_modules/ws/index.js 13:14-39
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

ERROR in ./node_modules/ws/lib/Extensions.js 2:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/lib/WebSocketServer.js 13:17-40
 @ ./node_modules/ws/index.js 11:12-44
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

ERROR in ./node_modules/ws/lib/Receiver.hixie.js 7:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/lib/WebSocket.js 20:20-47
 @ ./node_modules/ws/index.js 9:9-52
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

ERROR in ./node_modules/ws/lib/Receiver.js 7:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/index.js 13:14-39
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

ERROR in ./node_modules/ws/lib/Sender.hixie.js 8:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/lib/WebSocket.js 19:18-43
 @ ./node_modules/ws/index.js 9:9-52
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

ERROR in ./node_modules/ws/lib/Sender.js 8:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/index.js 12:12-35
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

ERROR in ./node_modules/ws/lib/WebSocket.js 10:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/index.js 9:9-52
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

ERROR in ./node_modules/ws/lib/WebSocketServer.js 7:11-26
Module not found: Error: Can't resolve 'util' in '/home/schiessl/Projekte/BitShares-Insight/test/node_modules/ws/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/ws/index.js 11:12-44
 @ ./node_modules/angular-websocket/dist/angular-websocket.js

8 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.75.0 compiled with 8 errors in 5287 ms
```

**Comment by ihorml** [comment]
@sschiessl-bcp fixed for Linux & force-pushed with resolved conflicts

**Comment by sschiessl-bcp** [comment]
Super, working nicely now

**Pull request merged**
